apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-deployment
  labels:
    app: udacity-capstone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone-app
  template:
    metadata:
      labels:
        app: udacity-capstone-app
    spec:
      containers:
        - name: udacity-capstone-app
          image: amitkhurana/capstone_img
          ports:
            - containerPort: 8080
