apiVersion: v1
kind: Service
metadata:
  name: uccapstoneproject
  labels:
    app: uccapstoneproject
spec:
  type: LoadBalancer
  selector:
    app: uccapstoneproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
